# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd02fa214ca19377ff1c4670808ee0e1fe9553eeb44a2c5312e1cff1f06a97bf4961a12a309a611a394dd0e8e863f8b9ef6c933abb916418ab219a682605ec3b

test:
  secret_key_base: 674af74a4fd036162b9bbe8500c18222dd0c7984d00f2d1bcebee26bce135102714c31732d71999eb6387113a5cd2fdd9da5ae5f809c1c81f45b8e52a9978461

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
